### ISSUE TITLE
Repository standardization

### ISSUE THREAD

**Issue by luxonauta** [dracula/ngenuity#1]
Hi @eduardovilke, we need to adjust some things to move forward, ok? ✨

We need to update the screenshot! Can you take a single capture at the closest possible resolution to 1728x1117 and PNG format?

**Comment by eduardovilke** [comment]
Hi @luxonauta, i made the change, added a better quality image. Can you see if it's correct now?

**Comment by luxonauta** [comment]
Hi @eduardovilke , sorry for the delay in responding 😅; it's excellent now! Thanks!
